<?php
/**
 * Julien Guittard Website
 *
 * @version   1.0
 * @author    Julien Guittard <julien.guittard@me.com>
 * @see       https://github.com/jguittard/julienguittard.com for the canonical source repository
 * @copyright Copyright (c) 2017 Julien Guittard. (https://julienguittard.com)
 */
?>
<div class="widget-author boxed push-down-30">
    <div class="widget-author__image-container">
        <div class="widget-author__avatar--blurred">
            <img src="//avatars2.githubusercontent.com/u/5320213?s=90&v=4" alt="Avatar image" width="90" height="90">
        </div>
        <img class="widget-author__avatar" src="//avatars2.githubusercontent.com/u/5320213?s=90&v=4" alt="Avatar image" width="90" height="90">
    </div>
    <div class="row">
        <div class="col-xs-10  col-xs-offset-1">
            <h4>Julien Guittard</h4>
            <p>Web Application Architect, Trainer, Blessed husband, Princesses Father.</p>
        </div>
    </div>
</div>
