<?php
/**
 * Julien Guittard Website
 *
 * @version   1.0
 * @author    Julien Guittard <julien.guittard@me.com>
 * @see       https://github.com/jguittard/julienguittard.com for the canonical source repository
 * @copyright Copyright (c) 2017 Julien Guittard. (https://julienguittard.com)
 */
?>
<footer class="footer">
    <div class="container">
        <div class="col-xs-12 col-md-3">
            <div class="widget-about push-down-30">

            </div>
        </div>
        <div class="col-xs-12 col-md-3">
            <div class="tags widget-tags">

            </div>
        </div>
        <div class="col-xs-12 col-md-3">
            <div class="widget-navigation push-down-30">

            </div>
        </div>
        <div class="col-xs-12 col-md-3">
            <div class="widget-contact push-down-30">

            </div>
        </div>
    </div>
</footer>
<section class="copyrights">
    <div class="container">
        <div class="row">
            <div class="col-xs-12  col-sm-6">
                Copyright 2009-<?= date('Y') ?> &copy; by Julien Guittard.
            </div>
            <div class="col-xs-12  col-sm-6">
                <div class="copyrights--right">
                    Made with <i class="glyphicon glyphicon-heart"></i> using
                    <a href="https://github.com/zendframework/zend-expressive" target="_blank">zend-expressive</a> and
                    <a href="http://php.net" target="_blank">PHP</a>.
                </div>
            </div>
        </div>
    </div>
</section>
