<?php
/**
 * Julien Guittard Website
 *
 * @version   1.0
 * @author    Julien Guittard <julien.guittard@me.com>
 * @see       https://github.com/jguittard/julienguittard.com for the canonical source repository
 * @copyright Copyright (c) 2017 Julien Guittard. (https://julienguittard.com)
 */
?>
<header class="header push-down-45" role="banner">
    <div class="container">
        <div class="logo pull-left">
            <a href="<?= $this->url('home'); ?>" rel="home">
                <img src="images/logo_long.png" alt="JG" width="580" height="140">
            </a>
        </div>

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#readable-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <nav class="navbar navbar-default" role="navigation">
            <div class="collapse navbar-collapse" id="readable-navbar-collapse">
                <?= $this->partial('layout::partials/navigation'); ?>
            </div>
        </nav>
    </div>
</header>
