<?php
/**
 * Julien Guittard Website
 *
 * @version   1.0
 * @author    Julien Guittard <julien.guittard@me.com>
 * @see       https://github.com/jguittard/julienguittard.com for the canonical source repository
 * @copyright Copyright (c) 2017 Julien Guittard. (https://julienguittard.com)
 */
?>
<head>
    <meta charset="utf-8" />
    <?= $this->headTitle('Julien Guittard')->setSeparator(' | ')->setAutoEscape(false) ?>
    <?= $this->headMeta()
             ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0')
             ->appendName('author', 'Julien Guittard')
             ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
             ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
             ->appendName('mobile-web-app-capable', 'yes')
             ->appendName('apple-mobile-web-app-capable', 'yes')
             ->appendName('application-name', 'JG.com')
             ->appendName('apple-mobile-web-app-title', 'JG.com')
             ->appendName('theme-color', '#70b49c')
             ->appendName('msapplication-navbutton-color', '#70b49c')
             ->appendName('apple-mobile-web-app-status-bar-style', 'black-translucent')
             ->appendName('msapplication-starturl', '/')
    ;
    $this->headLink([
        'rel' => 'icon',
        'type' => 'image/x-icon',
        'href' => '/favicon.ico',
    ]);
    $this->headLink([
        'rel' => 'manifest',
        'href' => '/manifest.json',
    ]);
    $this->headLink([
        'rel' => 'icon',
        'href' => '/icons/icon-128.png',
    ]);
    $this->headLink([
        'rel' => 'icon',
        'href' => '/icons/icon-192.png',
    ]);
    $this->headLink([
        'rel' => 'apple-touch-icon',
        'href' => '/icons/icon-120.png',
    ]);
    $this->headLink([
        'rel' => 'apple-touch-icon',
        'href' => '/icons/icon-120.png',
        'sizes' => '120x120',
    ]);
    $this->headLink([
        'rel' => 'apple-touch-icon',
        'href' => '/icons/icon-152.png',
        'sizes' => '152x152',
    ]);
    $this->headLink([
        'rel' => 'apple-touch-icon',
        'href' => '/icons/icon-167.png',
        'sizes' => '167x167',
    ]);
    $this->headLink([
        'rel' => 'apple-touch-icon',
        'href' => '/icons/icon-180.png',
        'sizes' => '180x180',
    ]);
    $this->headLink([
        'rel' => 'manifest',
        'href' => '/manifest.json',
    ]);
    $this->headLink()->prependStylesheet('/styles/main.css');
    echo $this->headLink(); ?>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <!-- Google Fonts -->
    <script type="text/javascript">
        WebFontConfig = {
            google: {
                families: ['Open+Sans:300,400,700:latin', 'Lato:700,900:latin']
            }
        };
        (function() {
            var wf = document.createElement('script');
            wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
                '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
            wf.type = 'text/javascript';
            wf.async = 'true';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(wf, s);
        })();
    </script>
    <?php
        $this->inlineScript()->prependFile('//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js')
                             ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js');
    ?>
