<?php
/**
 * Julien Guittard Website
 *
 * @version   1.0
 * @author    Julien Guittard <julien.guittard@me.com>
 * @see       https://github.com/jguittard/julienguittard.com for the canonical source repository
 * @copyright Copyright (c) 2017 Julien Guittard. (https://julienguittard.com)
 */
?>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <div class="boxed push-down-45">
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1">
                    <div class="contact">
                        <h2>Contact</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?= $this->partial('layout::partials/sidebar'); ?>
</div>
